// src/locales/index.js is auto-generated by `d2-app-scripts i18n generate`
// and gitignored (see .gitignore's `src/locales` entry), so it has no type
// declarations of its own. This file is deliberately NOT named `locales.d.ts`
// -- TypeScript will resolve a same-named declaration file as the module
// itself rather than as an ambient pattern match, which is exactly the
// collision that happens if this lives at src/locales.d.ts.
declare module '*/locales' {
  const i18n: {
    t: (key: string, options?: Record<string, unknown>) => string
  }
  export default i18n
}
